# netlify.toml (at your repo root)

[build]
  # run from frontend/
  base    = "frontend"
  # install & build your React app
  command = "npm install && npm run build"
  # publish from frontend/build
  publish = "build"

# Proxy API calls to Railway
[[redirects]]
  from   = "/api/*"
  to     = "https://sphinx-yachts-production.up.railway.app/api/:splat"
  status = 200

# Serve index.html for all other routes (SPA fallback)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
