[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "build"    # <-- NOT "frontend/build" when base="frontend"

[[redirects]]
  from   = "/api/*"
  to     = "https://sphinx-yachts-production.up.railway.app/api/:splat"
  status = 200
